import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/src/components/layout/Navbar";
import localFont from "next/font/local";

const causten = localFont({
  src: [
    {
      path: "../../../public/fonts/causten/Causten-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-causten",
});

export const metadata: Metadata = {
  title: "Pulso Verde",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${causten.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
